/* 
SCRIPT PURPOSE - THIS SCRIPT ISN USED TO CREATE A DATABASE NAMED 'DataWarehouse' AFTER CHECKING IF ITS ALREADY 
EXISTS OR NOT IF IT EXISTS IT IS DROPPED AND RECREATED. ADDITIONALLY THE SCRIPTS SETS UP THREE SCHEMAS IN THE
DATABASE : 'BRONZE','SILVER','GOLD'.

WARNING : RUNNING THIS SCRIPT WILL ENTIRELY DROP THE DataWarehouse database if exists all the data in the database 
will be deleted permanently . proceed with proper backup before execution of this script.

*/

USE MASTER;
GO
--DROP AND RECREATE THE DATABASE IF EXISTS--
USE master;
GO

-- DROP AND RECREATE DATABASE IF IT EXISTS
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'DataWarehouse')
BEGIN
    ALTER DATABASE DataWarehouse 
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

    DROP DATABASE DataWarehouse;
END;
GO

-- CREATE DATABASE
CREATE DATABASE DataWarehouse;
GO

USE DataWarehouse;
GO

-- CREATE SCHEMAS
CREATE SCHEMA bronze;
GO

CREATE SCHEMA silver;
GO

CREATE SCHEMA gold;
GO

